version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ftechnology-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ftechnology
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200'

volumes:
  postgres-data:
